### ISSUE TITLE
[BUG] Prospector fails pylint error - 1.13.x

### ISSUE THREAD

**Issue by robertalexa** [prospector-dev/prospector#703]
Hi,

Upgrading from 1.12.1 to any of the 1.13.x versions ends with with a pylint error on Django.

Python version used - 3.13

Unfortunately I understand too little about the chain from propesctor to pylint and how astroid intervenes, so I won't even pretend to make an assumption on this one.

Happy to do further testing if required. Here is a traceback of the error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/logging/config.py", line 583, in configure
    formatters[name] = self.configure_formatter(
                       ~~~~~~~~~~~~~~~~~~~~~~~~^
                                        formatters[name])
                                        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/logging/config.py", line 693, in configure_formatter
    result = self.configure_custom(config)
  File "/usr/local/lib/python3.13/logging/config.py", line 487, in configure_custom
    result = c(**kwargs)
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/django/utils/log.py", line 182, in __init__
    self.style = color_style()
                 ~~~~~~~~~~~^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/django/core/management/color.py", line 118, in color_style
    if not force_color and not supports_color():
                               ~~~~~~~~~~~~~~^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/django/core/management/color.py", line 54, in supports_color
    is_a_tty = hasattr(sys.stdout, "isatty") and sys.stdout.isatty()
                                                 ~~~~~~~~~~~~~~~~~^^
ValueError: I/O operation on uninitialized object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/prospector/run.py", line 87, in execute
    messages += tool.run(found_files)
                ~~~~~~~~^^^^^^^^^^^^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/prospector/tools/pylint/__init__.py", line 264, in run
    self._linter.check(self._args)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 699, in check
    with self._astroid_module_checker() as check_astroid_module:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 947, in _astroid_module_checker
    checker.open()
    ~~~~~~~~~~~~^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/pylint_django/checkers/foreign_key_strings.py", line 85, in open
    django.setup()
    ~~~~~~~~~~~~^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/django/utils/log.py", line 72, in configure_logging
    logging.config.dictConfig(DEFAULT_LOGGING)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/logging/config.py", line 935, in dictConfig
    dictConfigClass(config).configure()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/logging/config.py", line 586, in configure
    raise ValueError('Unable to configure '
                     'formatter %r' % name) from e
ValueError: Unable to configure formatter 'django.server'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hav-sentry/.local/bin/prospector", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/prospector/run.py", line 200, in main
    prospector.execute()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/hav-sentry/.local/lib/python3.13/site-packages/prospector/run.py", line 105, in execute
    raise FatalProspectorException(f"Tool {toolname} failed to run.") from ex
prospector.exceptions.FatalProspectorException: Tool pylint failed to run.
```

PS: @Pierre-Sassoulas I know you have helped tremendously migrating to the new python version and you have helped work through the snags of this. Any chance you can assist with this?

Thanks in advance

**Comment by sbrunner** [comment]
Hello,

What do you get with: `prospector --show-profile`?

CU
Stéphane

**Comment by robertalexa** [comment]
Hi @sbrunner 

Thanks for your assistance. See output below:

```
Messages
========

.
  Line: None
    pylint: failure / Tool pylint failed to run (exception was raised, re-run prospector with -X to see the stacktrace)



Profile
=======

autodetect: true
bandit:
  disable: []
  enable: []
  options: {}
  run: null
doc-warnings: true
dodgy:
  disable: []
  enable: []
  options: {}
  run: null
ignore-paths:
- app/apps/sql_models/migrations
ignore-patterns:
- (^|/)\..+
- ^tests?/?
- /tests?(/|$)
- .*/tests(/|$)
- (^|/)test_[_a-zA-Z0-9]+.py$
- (^|/)[_a-zA-Z0-9]+_tests?.py$
- (^|/)tests?.py
max-line-length: 120
mccabe:
  disable:
  - MC0001
  enable: []
  options:
    max-complexity: 10
  run: null
member-warnings: null
mypy:
  disable: []
  enable: []
  options: {}
  run: null
output-format: null
output-target: null
profile-validator:
  disable: []
  enable: []
  options: {}
  run: null
pycodestyle:
  disable:
  - E203
  enable: []
  full: true
  options:
    max-line-length: 120
    single-line-if-stmt: n
  run: null
pydocstyle:
  disable:
  - D203
  - D406
  - D204
  - D413
  - D407
  - D100
  - D408
  - D400
  - D212
  - D401
  - D000
  - D215
  - D409
  - D404
  - D104
  enable: []
  full: true
  options: {}
  run: true
pyflakes:
  disable: []
  enable: []
  options: {}
  run: null
pylint:
  disable:
  - bad-continuation
  - no-name-in-module
  - fixme
  - no-member
  - C0114
  enable: []
  options:
    max-attributes: 7
    max-branches: 12
    max-line-length: 120
    max-locals: 15
    max-module-lines: 1000
    max-parents: 7
    max-public-methods: 20
    max-returns: 6
    max-statements: 50
    min-public-methods: 1
  run: null
pyright:
  disable: []
  enable: []
  options: {}
  run: null
pyroma:
  disable:
  - PYR19
  - PYR16
  enable: []
  options: {}
  run: null
requirements: []
ruff:
  disable: []
  enable: []
  options: {}
  run: null
strictness: null
test-warnings: null
uses: []
vulture:
  disable: []
  enable: []
  options: {}
  run: null


Check Information
=================
         Started: 2024-11-19 11:33:31.247322
        Finished: 2024-11-19 11:33:56.356238
      Time Taken: 25.11 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, strictness_veryhigh, doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, profile-validator, pycodestyle, pydocstyle, pyflakes, pylint
  Messages Found: 1
 External Config: pylint: /opt/hav-backend/pyproject.toml
```

**Comment by carlio** [comment]
@robertalexa you run prospector with the `--direct-tool-stdout` flag? That worked for me when I got this stacktrace.

@sbrunner I ran into this myself on my own codebase, and it seems like the `CaptureOutput` wrapper to prevent spurious stdout/stderr output is what is causing this. I haven't figured out why yet, but it might help.
